text: ""
fontSize:
  default: "0.9rem"
  description: "Add a valid CSS value (eg.: 1rem, 10px etc)"
fontStyle:
  default: normal
  type: enum
  choices:
    - italic
    - normal
fontWeight:
  default: 700
  type: enum
  choices:
    - 400
    - 500
    - 600
    - 700
link: ""
bgColor: ""
  description: "Add a valid CSS color (eg.: red, blue, rgb(0,0,0), #f0f0f0 etc)"
bannerHeight:
  default: "2.4rem"
  description: "Add a valid CSS value (eg.: 1rem, 10px etc)"
